name: 'Execute python tests'

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Current working directory'
        type: string
        required: true
      install-redis:
        description: 'Parameter to check the whether redis is needed or not'
        type: boolean
        default: false
      runner_label:
        description: "Add runners for the GHA"
        default: '["self-hosted","platform-eng-ent"]'
        type: string
        required: false

jobs:
  execute-tests:
    runs-on:
      ${{ fromJSON(inputs.runner_label) }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install AWS CLI
        run: |
          python -m pip install --upgrade pip
          pip install awscli
        if: contains('self-hosted', ${{ inputs.runner_label }})

      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Setup redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: 6
        if: ${{ inputs.install-redis == true }}

      - name: Execute tests via script
        run: |
          sh ./.github/actions/scripts/check.sh ${{ inputs.working-directory }}/tests.py
